include ../../config.h

parmed::
	PYTHONPATH=$(PYTHONPATH) $(PYTHON) setup.py install -f $(PYTHON_INSTALL)

clean:
	/bin/rm -fr build/

skip:
	@echo ""
	@echo "Skipping installation of parmed."
	@echo ""

