#!/bin/sh

export AMBERCLASSICHOME="$(dirname "$(cd "$(dirname "$0")" && pwd)")"

$AMBERCLASSICHOME/bin/teLeap \
           -I$AMBERCLASSICHOME/dat/leap/prep \
           -I$AMBERCLASSICHOME/dat/leap/lib \
           -I$AMBERCLASSICHOME/dat/leap/parm \
           -I$AMBERCLASSICHOME/dat/leap/cmd \
            $*
