#!/bin/bash 

id=$1
resolution=$2

#--------------------------------------------------------------------------
#  1. Use metatwist to create a solvent density file from guv files:
#--------------------------------------------------------------------------

metatwist --dx $id.O.0.ccp4  --species O2-  --odx rho.O.0.ccp4  \
    --map rhoelreal --bulkdens 55.55 > metatwist.log
metatwist --dx $id.Na+.0.ccp4  --species Na+  --odx rho.Na+.0.ccp4  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log
metatwist --dx $id.Cl-.0.ccp4  --species Cl-  --odx rho.Cl-.0.ccp4  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log

metatwist --dx rho.O.0.ccp4 rho.Na+.0.ccp4 rho.Cl-.0.ccp4 \
     --odx solvent.ccp4 --species none >> metatwist.log


# ================== convert to proper axis order for SFALL
mapmask mapin solvent.ccp4 mapout a.map <<EOF > maps.log
AXIS Z X Y
EOF

grid=`echo | mapdump mapin a.map | awk '/Grid sampling on x, y, z ../{print $8,$9,$10}'`

# =================== run SFALL
sfall mapin a.map hklout sfalled.mtz <<EOF >> maps.log
mode sfcalc mapin
EOF

# =================== rename column labels for refmac
cad hklin1 sfalled.mtz hklout solvent.mtz <<EOF >> maps.log
labin file 1 E1=FC E2=PHIC
labou file 1 E1=Fpart1 E2=PHIpart1
EOF

/bin/rm -f sfalled.mtz a.map rho.*.ccp4  maps.log
