#!/bin/sh 

metatwist=$MSANDERHOME/bin/metatwist

#=============================================================================
#  Using RISM and metatwist to place waters around a solute.
#    (copy this script to your working directory, and edit it as needed.
#
#    (This example uses a KH closure and pure water as a solvent, just
#    to illustrate the ideas. There is next to no error checking.)
#=============================================================================

id=$1    # identifier for this calculation
         # inputs: $id.parm7, $id.rst7, $id.pdb

thresh=0.7  # threshold for including explicit waters at the centers
            # of negative Laplacian regions.  These will be in order
            # with the most probable ones first, so you can edit the
            # output pdb file to inclcude as many as you think you want.
            # Setting a smaller threshhold will give you more waters,
            # but with increasingly less connection to the rism density.

            # Current thinking: use a thresh value of about 0.5, then
            # use add_to_box to randomly pack in any remaining waters,
            # which don't have any particular justification in the RISM
            # density.

#  main output: $id.wat.pdb = $id.pdb + placed waters (occ=1, B=0)
#               wats.pdb: just oxygen positions, with estimated
#                         occupations and B-factors


if true; then
#---------------------------------------------------------------------------
# 2.  Run metatwist to to a Lapacian analysis on the solvent distributions:
#---------------------------------------------------------------------------

#$metatwist --dx $id.O.0.ccp4 --species O  \
#     --convolve 4 --sigma 1.0 --odx $id.O.lp.ccp4 > $id.O.lp

$metatwist --dx $id.MG.0.ccp4 --species Mg2+  \
     --convolve 4 --sigma 1.0 --odx $id.MG.lp.ccp4 > $id.MG.lp

#$metatwist --dx $id.Na+.0.ccp4 --species Na+  \
#     --convolve 4 --sigma 1.0 --odx $id.K+.lp.ccp4 > $id.Na+.lp

fi


if false; then
#---------------------------------------------------------------------------
# 3.  Place water molecules at the centers of the negative Laplacians:
#---------------------------------------------------------------------------

$metatwist --dx $id.O.0.ccp4 \
      --ldx $id.O.lp.ccp4 --map blobsper \
      --species O WAT --bulk 55.55 --threshold $thresh  > $id.blobs 

grep -v TER $id.O.0-$id.O.lp-blobs-centroid.pdb > wats.pdb

# ===== Add hydrogens using gwh

sed 's/END/TER/' $id.pdb > $id.wat.pdb
gwh -p $id.parm7 -w wats.pdb < $id.pdb >> $id.wat.pdb 2>> $id.blobs
  
fi

if true; then
#---------------------------------------------------------------------------
# 3.  Place ions at the centers of the negative Laplacians:
#---------------------------------------------------------------------------

$metatwist --dx $id.MG.0.ccp4 \
      --ldx $id.MG.lp.ccp4 --map blobsper \
      --species MG MG --bulk 1.0  --threshold $thresh  > $id.MG.blobs

grep -v TER $id.MG.0-$id.MG.lp-blobs-centroid.pdb > MG.pdb

#$metatwist --dx $id.K+.0.ccp4 \
#      --ldx $id.K+.lp.ccp4 --map blobsper \
#      --species K K --bulk 0.100 --threshold $thresh  > $id.K+.blobs
#
#grep -v TER $id.K+.0-$id.K+.lp-blobs-centroid.pdb > K+.pdb

fi
/bin/rm -f $id.MG.0-* 
