#!/bin/sh 

#=============================================================================
#    Running RISM
#    (copy this script to your working directory, and edit it as needed.
#
#=============================================================================

id=$1    # identifier for this calculation
         # inputs: $id.parm7, $id.rst7
xvv=$2   # xvv file for the solvent to be used

export OMP_NUM_THREADS=16
sander=/home/case/msander/bin/msander

cat > mdin.rism <<EOF
  single-point 3D-RISM calculation using the sander interface
 &cntrl
    ntx=1, nstlim=0, irism=1,
 /
 &rism
    periodic='pme',
    closure='kh','pse2',  tolerance=0.01,1e-6
    grdspc=0.35,0.35,0.35,
    mdiis_del=0.4, mdiis_nvec=20, maxstep=5000, mdiis_restart=50,
    solvcut=9.0,
    verbose=2, npropagate=0,
    apply_rism_force=0,
    volfmt='ccp4', ntwrism=1,
 /
EOF

$sander -O -i mdin.rism -o $id.pse2.r3d \
    -p $id.parm7 -c $id.rst7 -xvv $xvv -guv $id.pse2

/bin/rm -f mdin.rism restrt mdinfo 

