include ../../config.h

pysander:
	@echo "[PYSANDER] pip install"
	$(PYTHON) -m pip install . > setup.py.log

clean:
	/bin/rm -fr build/

skip:
	@echo ""
	@echo "Skipping installation of pysander."
	@echo ""
